# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='original',
            name='corrected_text',
            field=models.TextField(blank=True),
        ),
    ]
