# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0002_original_corrected_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Original',
            new_name='News',
        ),
    ]
