# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0003_auto_20170621_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsText',
        ),
    ]
