# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correct', '0004_auto_20170621_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstext',
            name='corrected_text',
        ),
    ]
